# -*- coding: utf-8 -*-
"""
Created on Tue Sep  8 13:18:01 2020

@author: David
"""
import unittest
import unittest.mock
from tool.feature_extraction.extractors.label_from_file import LabelFromFile
import pandas as pd

@unittest.mock.patch("pandas.read_csv")
class TestLabelFromFile(unittest.TestCase):
    def setUp(self):
        self.label_file = "labels.csv"
        self.label_column = "Type"
        self.id_column = "Sha1"

        self.labels = [1, 2, 3]
        self.index = [0, 1, 2]

    def test_init(self, patched):
        instance = LabelFromFile(self.label_file, self.label_column,
                                      self.id_column)
        patched.assert_called_once_with(
            self.label_file, index_col=self.id_column,
            usecols=[self.label_column, self.id_column])

    def test_process(self, patched):
        patched.return_value = pd.DataFrame(
            self.labels, index=self.index,
            columns=[self.label_column]
        )
        instance = LabelFromFile(self.label_file, self.label_column,
                                      self.id_column)
        self.assertEqual(
            instance.process(self.index[0]),
            {self.label_column: self.labels[self.index[0]],
             self.id_column: self.index[0]}
        )

    def test_process_error_not_found(self, patched):
        patched.return_value = pd.DataFrame()
        instance = LabelFromFile(self.label_file, self.label_column,
                                      self.id_column)
        self.assertRaises(ValueError, instance.process, 1)

    def test_process_error_duplicate(self, patched):
        patched.return_value = pd.DataFrame([0, 1], index=[0, 0],
            columns=[self.label_column])
        instance = LabelFromFile(self.label_file, self.label_column,
                                      self.id_column)
        self.assertRaises(ValueError, instance.process, 0)
